<?php
if ( ! defined( 'ABSPATH' ) ) exit;
class SWCS_Admin {
 public static function init(){add_action('admin_menu',array(__CLASS__,'menu'));add_action('admin_post_swcs_save_settings',array(__CLASS__,'save_settings'));add_action('admin_post_swcs_download_catalog',array(__CLASS__,'download_catalog'));}
 public static function menu(){add_menu_page('Stricker Catalog Sync','Stricker Catalog','manage_options','swcs',array(__CLASS__,'dashboard'),'dashicons-download',56);}
 private static function notice(){ $n=get_transient('swcs_notice_'.get_current_user_id());if($n){delete_transient('swcs_notice_'.get_current_user_id());echo '<div class="notice notice-'.esc_attr($n['type']).' is-dismissible"><p>'.esc_html($n['message']).'</p></div>';}}
 public static function dashboard(){if(!current_user_can('manage_options'))return;$key=SWCS_Catalog::get_access_key();$language=SWCS_Catalog::get_language();$status=SWCS_Catalog::get_download_status();$page=isset($_GET['swcs_product_page'])?max(1,(int)$_GET['swcs_product_page']):1;echo '<div class="wrap"><h1>Stricker Catalog Sync</h1>';self::notice();echo '<p>Versão '.esc_html(SWCS_VERSION).'. Catálogos grandes são baixados em background e processados localmente.</p>';echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('swcs_save_settings');echo '<input type="hidden" name="action" value="swcs_save_settings"><table class="form-table"><tr><th>Access Key</th><td><input type="password" class="regular-text" name="access_key" value="'.esc_attr($key).'" autocomplete="off"></td></tr><tr><th>Idioma</th><td><select name="language"><option value="PT" '.selected($language,'PT',false).'>Português (PT)</option><option value="EN" '.selected($language,'EN',false).'>English (EN)</option></select></td></tr></table>';submit_button('Salvar configurações');echo '</form><hr><h2>Catálogo</h2>';self::catalog_button('producttypes','Baixar ProductTypes');echo ' ';self::catalog_button('products','Baixar Products');if(isset($status['status'])&&$status['status']!=='idle'){echo '<div style="margin:20px 0;padding:12px;background:#fff;border-left:4px solid '.('error'===$status['status']?'#d63638':'#00a32a').'"><strong>Status:</strong> '.esc_html($status['status']).' &nbsp; <strong>Tipo:</strong> '.esc_html($status['type']??'');if(isset($status['bytes']))echo '<br><strong>Tamanho:</strong> '.esc_html(size_format($status['bytes']));if(isset($status['finished_at']))echo '<br><strong>Concluído:</strong> '.esc_html($status['finished_at']);if(isset($status['message']))echo '<br><strong>Mensagem:</strong> '.esc_html($status['message']);echo '</div>';}
 if(isset($status['type'])&&$status['type']==='products'&&$status['status']==='completed'){$data=SWCS_Catalog::get_products_page($page,25);echo '<hr><h2>Produtos</h2>';if(is_wp_error($data)){echo '<div class="notice notice-error"><p>'.esc_html($data->get_error_message()).'</p></div>';}else{echo '<p><strong>'.esc_html(number_format_i18n($data['total'])).'</strong> produtos identificados. Página '.esc_html($data['page']).' de '.esc_html($data['pages']).'.</p><table class="widefat striped"><thead><tr><th>Referência / SKU</th><th>Nome</th><th>Descrição</th><th>Características</th></tr></thead><tbody>';foreach($data['items'] as $p){$f=array();if($p['has_colors']!=='')$f[]='Cores: '.$p['has_colors'];if($p['has_sizes']!=='')$f[]='Tamanhos: '.$p['has_sizes'];if($p['has_capacitys']!=='')$f[]='Capacidades: '.$p['has_capacitys'];if($p['is_textil']!=='')$f[]='Têxtil: '.$p['is_textil'];echo '<tr><td>'.esc_html($p['reference']).'</td><td>'.esc_html($p['name']).'</td><td>'.esc_html(wp_trim_words(wp_strip_all_tags($p['description']),28)).'</td><td>'.esc_html(implode(' | ',$f)).'</td></tr>';}echo '</tbody></table>';if($data['pages']>1){echo '<div class="tablenav"><div class="tablenav-pages" style="margin:12px 0">';for($i=1;$i<=$data['pages'];$i++){echo $i===$data['page']?' <strong>'.$i.'</strong> ':' <a href="'.esc_url(add_query_arg(array('page'=>'swcs','swcs_product_page'=>$i),admin_url('admin.php'))).'">'.$i.'</a> ';}echo '</div></div>';}}}
 echo '</div>';}
 private static function catalog_button($type,$label){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="display:inline-block">';wp_nonce_field('swcs_download_catalog_'.$type);echo '<input type="hidden" name="action" value="swcs_download_catalog"><input type="hidden" name="catalog_type" value="'.esc_attr($type).'">';submit_button($label,'secondary','submit',false);echo '</form>';}
 public static function save_settings(){if(!current_user_can('manage_options'))wp_die('Sem permissão.');check_admin_referer('swcs_save_settings');$key=isset($_POST['access_key'])?sanitize_text_field(wp_unslash($_POST['access_key'])):'';$language=isset($_POST['language'])?sanitize_key(wp_unslash($_POST['language'])):'PT';if(!in_array($language,array('PT','EN'),true))$language='PT';SWCS_Catalog::save_settings($key,$language);self::set_notice('success','Configurações salvas com sucesso.');wp_safe_redirect(admin_url('admin.php?page=swcs'));exit;}
 public static function download_catalog(){if(!current_user_can('manage_options'))wp_die('Sem permissão.');$type=isset($_POST['catalog_type'])?sanitize_key(wp_unslash($_POST['catalog_type'])):'producttypes';check_admin_referer('swcs_download_catalog_'.$type);if(!in_array($type,array('producttypes','products'),true))self::set_notice('error','Tipo de catálogo inválido.');elseif(SWCS_Catalog::get_access_key()==='')self::set_notice('error','Access Key não configurada.');else{SWCS_Catalog::request_download($type);self::set_notice('success','Download de '.$type.' colocado em segundo plano.');}wp_safe_redirect(admin_url('admin.php?page=swcs'));exit;}
 private static function set_notice($type,$message){set_transient('swcs_notice_'.get_current_user_id(),array('type'=>$type,'message'=>$message),60);}
}
